// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable error codes for the frontend.
 *
 * These codes allow the frontend to programmatically handle errors
 * without parsing error messages.
 */
export type ErrorCode = "CHANNEL_NOT_FOUND" | "BLOCK_NOT_FOUND" | "CONNECTION_NOT_FOUND" | "VALIDATION_ERROR" | "DUPLICATE_ERROR" | "DATABASE_ERROR" | "INITIALIZATION_ERROR" | "MEDIA_ERROR" | "INTERNAL_ERROR";
