// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The content of a block.
 *
 * Supports Text, Link, Image, Video, and Audio types.
 * Future types: Code.
 */
export type BlockContent = { "type": "text", 
/**
 * The text body.
 */
body: string, } | { "type": "link", 
/**
 * The URL.
 */
url: string, 
/**
 * Optional title (often extracted from the page).
 */
title: string | null, 
/**
 * Optional description (often extracted from meta tags).
 */
description: string | null, 
/**
 * Alt text for accessibility.
 */
alt_text: string | null, } | { "type": "image", 
/**
 * Relative path within media directory: "images/{uuid}.{ext}"
 */
file_path: string, 
/**
 * Original URL where image was downloaded from.
 */
original_url: string | null, 
/**
 * Image width in pixels.
 */
width: number | null, 
/**
 * Image height in pixels.
 */
height: number | null, 
/**
 * MIME type: "image/jpeg", "image/png", etc.
 */
mime_type: string, 
/**
 * Alt text for accessibility.
 */
alt_text: string | null, } | { "type": "video", 
/**
 * Relative path within media directory: "videos/{uuid}.{ext}"
 */
file_path: string, 
/**
 * Original URL where video was downloaded from.
 */
original_url: string | null, 
/**
 * Video width in pixels.
 */
width: number | null, 
/**
 * Video height in pixels.
 */
height: number | null, 
/**
 * Duration in seconds.
 */
duration: number | null, 
/**
 * MIME type: "video/mp4", "video/webm", etc.
 */
mime_type: string, 
/**
 * Alt text for accessibility.
 */
alt_text: string | null, } | { "type": "audio", 
/**
 * Relative path within media directory: "audio/{uuid}.{ext}"
 */
file_path: string, 
/**
 * Original URL where audio was downloaded from.
 */
original_url: string | null, 
/**
 * Duration in seconds.
 */
duration: number | null, 
/**
 * MIME type: "audio/mpeg", "audio/ogg", etc.
 */
mime_type: string, 
/**
 * Title from ID3 tags or filename.
 */
title: string | null, 
/**
 * Artist from ID3 tags.
 */
artist: string | null, };
