// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents an optional field update.
 *
 * This solves the `Option<Option<T>>` problem where we need to distinguish between:
 * - Not updating a field (Keep)
 * - Clearing a field to None (Clear)
 * - Setting a field to a new value (Set)
 */
export type FieldUpdate<T> = { "action": "keep" } | { "action": "clear" } | { "action": "set", "value": T };
